default:
  # ==== DEFINE PARAMETER FOR THE CURRENT RUN ====
  sitecall_mode: kompas # imads/kompas
  tf: # this will determine homotypic / heterotypic
    - ets1
    - runx1
  genomever: hg38

  # Below is the general part, it is okay to put any information since run specific
  # information is provided above.
  # ==== ESCORE ====
  escore_map_paths: /Users/vincentiusmartin/Research/chip2gcPBM/resources/escores/index_short_to_long.csv
  escore_short_paths:
    ets1: /Users/vincentiusmartin/Research/chip2gcPBM/resources/escores/ets1_escores.txt
  escore_long_paths:
    ets1: /Users/faricazjj/Box/homotf/chip2probe/chip2probe/data/escores/Ets1_8mers_11111111.txt
    runx1: /Users/faricazjj/Box/homotf/chip2probe/chip2probe/data/escores/Runx1_8mers_11111111.txt

  imads_cutoff:
    ets1: 0.2128
    runx1: 0.3061

  # IMADS
  imads:
    ets1:
      cores:
        - GGAA
        - GGAT
      modelpaths:
        - /Users/vincentiusmartin/Research/chip2gcPBM/resources/imads_files/models/ets1/ETS1_100nM_Bound_filtered_normalized_transformed_20bp_GGAA_1a2a3mer_format.model
        - /Users/vincentiusmartin/Research/chip2gcPBM/resources/imads_files/models/ets1/ETS1_100nM_Bound_filtered_normalized_transformed_20bp_GGAT_1a2a3mer_format.model
      bedpath: /Users/vincentiusmartin/Research/chip2gcPBM/resources/imads_files/predictions/hg19_0005_Ets1_filtered.bed
      cutoff: 0.2128
    runx1:
      cores:
        - GAGGT
        - GCGGC
        - GCGGG
        - GCGGT
        - GTGGC
        - GTGGG
        - GTGGT

  # KOMPAS
  kompas:
    ets1:
      alignpath: /Users/vincentiusmartin/Research/chip2gcPBM/chip2probe/chip2probe/kompas/ets1_kmer_alignment.txt
      pwm_core_start: 3
      pwm_core_end: 7
    runx1:
      alignpath: /Users/vincentiusmartin/Research/chip2gcPBM/chip2probe/chip2probe/kompas/runx1_kmer_alignment.txt
      pwm_core_start: 4
      pwm_core_end: 9
